version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=HJsyuzebns7676
      - DB_DATABASE=bookstackapp
    volumes:
      - bookstack-web-data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=HJsyuzebns7676
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=HJsyuzebns7676
    volumes:
      - bookstack-db-data:/var/lib/mysql
      - bookstack-db-config:/config
    restart: unless-stopped

volumes:
  bookstack-web-data:
    driver: local
  bookstack-db-data:
    driver: local
  bookstack-db-config:
    driver: local
 