version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      TZ: Europe/Paris
    volumes:
      - db-data:/var/lib/postgresql/data

  zabbix:
    image: zabbix/zabbix-server-pgsql:latest
    depends_on:
      - db
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_DATABASE_SCHEMA: zabbix
    volumes:
      - zabbix-data:/var/lib/zabbix
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    depends_on:
      - db
      - zabbix
    ports:
      - "8095:8080"
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix
    restart: always

volumes:
  db-data:
  zabbix-data:
